dist: trusty
sudo: required
language: node_js
node_js:
  - "14.17.0"
install:
  - npm install
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "sgt-fields"
jdk:
  - openjdk11
script:
  - npm test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'